# Generated by Django 4.1.4 on 2022-12-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='about')),
                ('subtitle', models.TextField(max_length=500)),
                ('aboutme', models.TextField(max_length=1000)),
                ('tw_link', models.URLField()),
                ('tk_in_link', models.URLField()),
                ('github_link', models.URLField()),
            ],
        ),
    ]
